projeto_distribueasy/app_cadastro_cliente/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('entrada', tela_entrada, name='tela_entrada'),
    path('usuarios/listar', listar_usuarios, name='listar_usuarios'),
    path('usuarios/listar/<int:id>', listar_usuarios_id, name='listar_usuarios_id'),
    path('usuarios/editar/<int:id>', editar_usuarios, name='editar_usuarios'),
    path('usuarios/excluir/<int:id>', excluir_usuarios, name='excluir_usuarios'),
    path('usuarios/cadastro', cadastrar_usuarios, name='cadastrar_usuarios'),

]

projeto_distribueasy/projeto_distribueasy/urls.py
from django.contrib import admin
from django.urls import path, include
from app_cadastro_cliente import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_cadastro_cliente.urls')),
]

projeto_distribueasy/app_cadastro_cliente/models.py
from django.db import models
from .validators import *

# Create your models here.
class CPFField(models.CharField):
    default_validators = [validate_cpf_cnpj]

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('max_length', 14)
        super().__init__(*args, **kwargs)

class Cliente(models.Model):
    cliente_CHOICE = (
        ('PF', 'Pessoa Física'),
        ('PJ', 'Pessoa Jurídica')
    )
    tipo_cliente = models.CharField(max_length=2, choices=cliente_CHOICE)
    cliente_cpf_cnpj = CPFField('CPF/CNPJ')
    cliente_nome = models.CharField(max_length=50)
    cliente_email = models.EmailField(max_length=50)
    cliente_telefone = models.CharField(max_length=14)
    cliente_telefone2 = models.CharField(max_length=14, blank=True, null=True)
    cliente_rua = models.CharField(max_length=50)
    cliente_bairro = models.CharField(max_length=50)
    cliente_cidade = models.CharField(max_length=50)
    estado_CHOICE = (
        ('AC','Acre'),
        ('AL','Alagoas'),
        ('AP','Amapá'),
        ('AM','Amazonas'),
        ('BA','Bahia'),
        ('CE','Ceará'),
        ('DF','Distrito Federal'),
        ('ES','Espírito Santo'),
        ('GO','Goiás'),
        ('MA','Maranhão'),
        ('MT','Mato Grosso'),
        ('MS','Mato Grosso do Sul'),
        ('MG','Minas Gerais'),
        ('PA','Pará'),
        ('PB','Paraíba'),
        ('PE','Pernambuco'),
        ('PI','Piauí'),
        ('RJ','Rio de Janeiro'),
        ('RN','Rio Grande do Norte'),
        ('RS','Rio Grande do Sul'),
        ('RO','Rondônia'),
        ('RR','Roraima'),
        ('SC','Santa Catarina'),
        ('SP','São Paulo'),
        ('SE','Sergipe'),
        ('TO','Tocantins')
    )
    cliente_estado = models.CharField(max_length=2,choices=estado_CHOICE)
    cliente_numero_casa = models.CharField(max_length=10)
    cliente_complemento = models.CharField(max_length=50)
    cliente_cep = models.CharField(max_length=18)
    cliente_data_registro = models.DateTimeField(auto_now_add=True)
    cliente_data_edicao = models.DateTimeField(auto_now_add=True)
    
    categoria_CHOICES = [
        ('F', 'Fornecedor'),
        ('C', 'Consumidor')
    ]
    cliente_categoria = models.CharField(max_length=1, choices= categoria_CHOICES)

projeto_distribueasy/app_cadastro_cliente/forms.py
# forms.py
from django import forms
from .models import Cliente
from .validators import *


class ClienteForm(forms.ModelForm):
    cliente_estado = forms.CharField(label='Estado', required=False)
    cliente_municipio = forms.CharField(label='Município', required=False)

    class Meta:
        model = Cliente
        fields = ['tipo_cliente', 'cliente_cpf_cnpj', 'cliente_nome', 'cliente_email', 'cliente_telefone', 'cliente_telefone2', 'cliente_rua', 'cliente_bairro', 'cliente_cidade', 'cliente_estado', 'cliente_municipio', 'cliente_numero_casa', 'cliente_complemento', 'cliente_cep', 'cliente_categoria']
    
    widgets = {
        'cliente_cpf_cnpj': forms.TextInput(attrs={'class': 'form-control only-digits'}),
        # Adicione outros widgets conforme necessário para os outros campos
    }
    
    cliente_categoria = forms.ChoiceField(choices=Cliente.categoria_CHOICES, widget=forms.RadioSelect)
 
    
    def clean_cliente_cep(self):
        cep = self.cleaned_data['cliente_cep']
        
        informacoes_endereco = obter_endereco(cep)

        if not informacoes_endereco:
            raise forms.ValidationError('CEP inválido ou não encontrado', code='invalid_cep')

        # Atualize os campos do endereço no formulário
        self.cleaned_data['cliente_cidade'] = informacoes_endereco.get('localidade', '')
        self.cleaned_data['cliente_estado'] = informacoes_endereco.get('uf', '')
        self.cleaned_data['cliente_bairro'] = informacoes_endereco.get('bairro', '')
        self.cleaned_data['cliente_rua'] = informacoes_endereco.get('logradouro', '')

        return cep

    
    def clean(self):
        cleaned_data = super().clean()
        tipo_cliente = cleaned_data.get('tipo_cliente')
        cliente_cpf_cnpj = cleaned_data.get('cliente_cpf_cnpj')

        if tipo_cliente and cliente_cpf_cnpj:
            validate_cpf_cnpj(cliente_cpf_cnpj)

        # Adicione outras validações conforme necessário

        return cleaned_data
    
    

projeto_distribueasy/app_cadastro_cliente/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.
def tela_entrada(request):
    return render(request, 'usuarios/tela_entrada.html')

def listar_usuarios(request):
    usuarios = Cliente.objects.all()
    return render(request,'usuarios/listar_usuarios.html', {'usuarios': usuarios})

def listar_usuarios_id(request, id):
    usuarios_id = Cliente.objects.get(id=id)
    return render(request, 'usuarios/listar_usuarios_id.html', {'usuarios_id': usuarios_id})

def cadastrar_usuarios(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listar_usuarios')
    else:
        form = ClienteForm()
    return render(request, 'usuarios/cadastrar_usuarios.html', {'form': form})

def editar_usuarios(request, id):
    usuario = Cliente.objects.get(id=id)
    if request.method == 'POST':
        form = ClienteForm(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            return redirect('listar_usuarios_id', id=id)
    else:
        form = ClienteForm(instance=usuario)
    return render(request, 'usuarios/cadastrar_usuarios.html', {'form': form, 'editar': True, 'usuario_id': id})


def excluir_usuarios(request,id):
    excluir_usuarios = Cliente.objects.get(id=id)
    if request.method == 'POST':
        excluir_usuarios.delete()
        return redirect('listar_usuarios')
    return render(request, 'usuarios/excluir_usuarios.html', {'excluir_usuarios':excluir_usuarios})

projeto_distribueasy/app_cadastro_cliente/templates/usuarios/base.html
{% load static %}
<!doctype html>
<html lang="pt-br">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static '/css/base.css' %}">
    <!-- Bootstrap CSS -->
    
    <title>Cadastro</title>
</head>
<body>
    <nav style="background-color: black !important;" class="navbar navbar-light bg-light navbar-divisor">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'tela_entrada' %}">
                <img src="{% static '/images/distribueasy-logo.png' %}" alt="" width="100" height="100" class="d-inline-block align-text-center">
                <strong style="color: orangered; font-family: Verdana;">DistribuEasy</strong>
            </a>
        </div>
    </nav>
    
    {% block conteudo %}

    {% endblock %}

    <!-- Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

projeto_distribueasy/app_cadastro_cliente/templates/usuarios/cadastrar_usuarios.html
{% extends 'usuarios/base.html'%}

{% load meus_filtros %}
{% load static %}

{% block conteudo %}


<link rel="stylesheet" href="{% static 'css/radio_select.css' %}">
<link rel="stylesheet" href="{% static 'css/formulario.css' %}">


<body>
    <main class="container formulario-container">
        
        <form method="post" action="{% if editar %}{% url 'editar_usuarios' usuario_id %}{% else %}{% url 'cadastrar_usuarios' %}?origem=cadastrar{% endif %}" class="novalidate">
            
            {% csrf_token %}
            <br>

            <div class="form-group">
                <label>Tipo de Categoria:</label>
            </div>

            <div class="form-group" id="cliente_categoria">
                {% for radio in form.cliente_categoria %}
                    {{ radio.tag }} {{ radio.choice_label }}
                {% endfor %}
            </div>

            <div class="form-group">
                {{ form.tipo_cliente.errors }}
                <label for="id_tipo_cliente">Tipo de Cliente:</label>
                {{ form.tipo_cliente }}
            </div>

            <div class="all-info hidden form-control">
                {{ form.cliente_cpf_cnpj.errors }}
                <label for="id_cliente_cpf_cnpj" name="cliente_cpf_cnpj">CPF/CNPJ: </label>
                
                {% if not editar %}
                    <input id="cpfcnpj" type="text" placeholder="digite o CPF ou CNPJ" name="{{ form.cliente_cpf_cnpj.name }}" value="{{ form.cliente_cpf_cnpj.value|default:'' }}" class="form-control visible-cpfcnpj">
                {% else %}
                    <input type="text" name="{{ form.cliente_cpf_cnpj.name }}" value="{{ form.cliente_cpf_cnpj.value }}" readonly>
                {% endif %}
                
                {{ form.cliente_nome.errors }}
                <label for="id_cliente_nome">Nome: </label>
                {{ form.cliente_nome|addclass:'form-control' }}
            </div>
            
            <div class="all-info hidden form-control">
                {{ form.cliente_email.errors }}
                <label>E-mail:</label>
                {{ form.cliente_email|addclass:'form-control' }}
            </div>

            <div class="all-info hidden form-control">
                {{ form.cliente_telefone.errors }}
                <label>Telefone:</label>
                {{ form.cliente_telefone|addclass:'form-control' }}
            </div>

            <div class="all-info hidden form-control">
                <label>Outro (opcional):</label>
                {{ form.cliente_telefone2|addclass:'form-control' }}
            </div>
            
            <div class="all-info hidden form-control">
                {{ form.cliente_cep.errors }}
                <label>CEP:</label>
                {{ form.cliente_cep|addclass:'form-control' }}
            </div>

            <div class="all-info hidden form-control">
                <label>Rua:</label>
                {{ form.cliente_rua|addclass:'form-control' }}
            </div>

            <div class="all-info hidden form-control">
                <label>Bairro:</label>
                {{ form.cliente_bairro|addclass:'form-control' }}
            </div>

            <div class="all-info hidden form-control">
                <label>Cidade:</label>
                {{ form.cliente_cidade|addclass:'form-control' }}
            </div>

            <div class="all-info hidden form-control">
                <label>Estado:</label>
                {{ form.cliente_estado|addclass:'form-control' }}
            </div>

            <div class="all-info hidden form-control">
                <label>Número:</label>
                {{ form.cliente_numero_casa|addclass:'form-control' }}
            </div>

            <div class="all-info hidden form-control">
                <label>Complemento (opcional):</label>
                {{ form.cliente_complemento|addclass:'form-control' }}
            </div>

            <div>
                <input type="submit" value="Cadastrar" class="btn reg-button">
                <button onclick="backButton()" class="btn back-button"><a>Voltar</a></button>
            </div>
        </form>
    </main>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://unpkg.com/imask"></script>
    <script src="{% static 'js/tipo_cliente.js' %}"> </script>
    <script src="{% static 'js/exibir_endereco.js' %}"> </script>
    <script src="{% static 'js/back_button.js' %}"></script>
    <script src="{% static 'js/only_numbers.js' %}"></script>
    
        <script>
                var inputElement = document.getElementById('cpfcnpj');
                var visibleInput = document.querySelector('.visible-cpfcnpj');  // Certifique-se de que esta classe esteja correta
                var inputValue = visibleInput.value.trim().replace(/[^\d]/g, '');


                if (inputElement && visibleInput) {
                    // Recupere a máscara anterior
                    var maskCpfOuCnpj = IMask(visibleInput, {
                        mask: [
                            {
                                mask: '000.000.000-00',
                                maxLength: 11
                            },
                            {
                                mask: '00.000.000/0000-00'
                            }
                        ],
                        // Defina o comportamento para manter o valor do campo sem a máscara
                        prepare: function (str) {
                            return str.replace(/[^0-9]+/g, '');
                        }
                    });

                    // Adicione o evento de input ao campo visível
                    visibleInput.addEventListener('input', function () {
                        var inputValue = visibleInput.value.replace(/[^\d]/g, '');  // Remova caracteres não numéricos
                        maskCpfOuCnpj.updateValue(inputValue);  // Atualize o valor com a nova entrada
                    });

                    // Sincronize a máscara quando o campo visível receber o foco
                    visibleInput.addEventListener('focus', function () {
                        maskCpfOuCnpj.updateValue();
                    });

                    // Sincronize a máscara quando o campo oculto receber o foco
                    inputElement.addEventListener('focus', function () {
                        maskCpfOuCnpj.updateValue();
                    });

                    // Sincronize a máscara antes do envio do formulário
                    document.querySelector('form').addEventListener('submit', function () {
                        maskCpfOuCnpj.destroy(); 
                    });
                }
    </script>

</body>

{% endblock %}

projeto_distribueasy/app_cadastro_cliente/templates/usuarios/listar_usuarios.html
{% extends 'usuarios/base.html' %}
{% load static %}
{% load meus_filtros %}
{% block conteudo %}

<link rel="stylesheet"  href="{% static '/css/listar.css' %}">

<br>
<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Categoria: </th>
                <th>Tipo:</th>
                <th>CPF/CNPJ:</th>
                <th>Nome:</th>
                <th>E-mail:</th>
                <th>Telefone:</th>
                <th>Telefone2:</th>
                <th>Rua:</th>
                <th>Bairro:</th>
                <th>Cidade:</th>
                <th>Estado:</th>
                <th>Número:</th>
                <th>Complemento:</th>
                <th>CEP:</th>
                <th>Data de Registro:</th>
                <th>Ações:</th>
            </tr>
        </thead>
        <tbody>
            {% for i in usuarios %}
            <tr>
                <td>{{i.get_cliente_categoria_display}}</td>
                <td>{{i.tipo_cliente}}</td>
                <td>{{i.cliente_cpf_cnpj}}</td>
                <td>{{i.cliente_nome}}</td>
                <td>{{i.cliente_email}}</td>
                <td>{{i.cliente_telefone}}</td>
                <td>{{i.cliente_telefone2}}</td>
                <td>{{i.cliente_rua}}</td>
                <td>{{i.cliente_bairro}}</td>
                <td>{{i.cliente_cidade}}</td>
                <td>{{i.cliente_estado}}</td>
                <td>{{i.cliente_numero_casa}}</td>
                <td>{{i.cliente_complemento}}</td>
                <td>{{i.cliente_cep}}</td>
                <td>{{i.cliente_data_registro|date:"d-m-Y H:i"}}</td>
                <td>
                    <a href="{% url 'listar_usuarios_id' i.id %}">Consultar</a>
                </td>
            </tr>
            
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

projeto_distribueasy/app_cadastro_cliente/templates/usuarios/listar_usuarios_id.html
{% extends 'usuarios/base.html' %}
{% load static %}
{% load meus_filtros %}
{% block conteudo %}
<link rel="stylesheet" href="{% static 'css/buttons.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="{% static 'js/excluir_cliente.js' %}"></script>

<body>
    <div class="card">
        <div class="card-header">
            Dados do Cliente
        </div>
        <div class="card-body">
            <h5 class="card-title">Tipo de Cliente: {{ usuarios_id.tipo_cliente|tipo_cliente_extenso }}</h5>
            <h5 class="card-title">CPF/CNPJ: {{usuarios_id.cliente_cpf_cnpj}}</h5>
            <h5 class="card-title">Nome: {{usuarios_id.cliente_nome}}</h5>
            <h5 class="card-title">E-mail: {{usuarios_id.cliente_email}}</h5>
            <h5 class="card-title">Telefone: {{usuarios_id.cliente_telefone}}</h5>
            <h5 class="card-title">Outro: {{usuarios_id.cliente_telefone2}}</h5>
            <h5 class="card-title">Rua: {{usuarios_id.cliente_rua}}</h5>
            <h5 class="card-title">Bairro: {{usuarios_id.cliente_bairro}}</h5>
            <h5 class="card-title">Cidade: {{usuarios_id.cliente_cidade}}</h5>
            <h5 class="card-title">Estado: {{usuarios_id.cliente_estado}}</h5>
            <h5 class="card-title">Número: {{usuarios_id.cliente_numero_casa}}</h5>
            <h5 class="card-title">Complemento: {{usuarios_id.cliente_complemento}}</h5>
            <h5 class="card-title">CEP: {{usuarios_id.cliente_cep}}</h5>
            <h5 class="card-title">Cadastrado em: {{usuarios_id.cliente_data_registro}}</h5>
        </div>
       
    <form method="post" action="{% url 'excluir_usuarios' usuarios_id.id %}" style="display:inline;" id="deleteForm">
                    {% csrf_token %}
                    <a href="{% url 'editar_usuarios' usuarios_id.id %}" class="btn edit-button">Editar</a>
                     <!-- Botão de Excluir com Modal -->
                    <button type="button" class="btn remove-button" data-toggle="modal" data-target="#confirmacaoModal">Excluir</button>
                    <a href="{% url 'listar_usuarios' %}" class="btn back-button">Voltar</a>

                    <!-- Modal de Confirmação de Exclusão -->
                    <div class="modal fade" id="confirmacaoModal" tabindex="-1" role="dialog" aria-labelledby="confirmacaoModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="confirmacaoModalLabel">Confirmar Exclusão</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Tem certeza que deseja excluir este cliente?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                        <button type="button" class="btn btn-danger" onclick="excluirCliente()">Excluir</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
        </form>
    </div>

   
    
</body>

{% endblock %}

projeto_distribueasy/app_cadastro_cliente/templates/usuarios/tela_entrada.html
{% extends 'usuarios/base.html' %}

{% block conteudo %}
<h5 style="color: orangered; font-weight: bold; font-family: Verdana; text-align: center;" id='bem-vindo'>BEM VINDO!</h5>

  
    <div class="d-flex flex-column justify-content-center align-items-center vh-100">
        
        <div class="form-floating mb-3">
            <input type="email" class="form-control small-input" id="usuario" placeholder="nome@exemplo.com">
            <label for="usuario">Usuário</label>
        </div>
        <div class="form-floating mb-3">
            <input type="password" class="form-control small-input" id="senha" placeholder="Password">
            <label for="senha">Senha</label>
        </div>

        <div class="d-grid gap-3">
            <button class="btn btn-primary small-button" type="button" style="background-color: black; border-color: orangered; font-family: Verdana; color: orangered; font-weight: bold;">
                Entrar</button>
            <a href="{% url 'cadastrar_usuarios'%}"><button class="btn btn-primary small-button" type="button" style="background-color: black; border-color: orangered; font-family: Verdana; color: orangered; font-weight: bold;">
                Cadastre-se</button></a>
        </div>
    </div>

{% endblock %}